=== MagisterVasader/Epam-labs/lab-3-maven/src/main/resources/planes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.example.org/planes"
        xmlns:tns="https://www.example.org/planes" elementFormDefault="qualified">

    <simpleType name="parameter">
        <restriction base="double">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>

    <simpleType name="weapon">
        <restriction base="double">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>

    <simpleType name="AARocket">
        <restriction base="positiveInteger">
            <minInclusive value="0"/>
            <maxInclusive value="20"/>
        </restriction>
    </simpleType>

    <simpleType name="AERocket">
        <restriction base="positiveInteger">
            <minInclusive value="0"/>
            <maxInclusive value="10"/>
        </restriction>
    </simpleType>

    <complexType name="ammo">
        <attribute name="weapon" type="tns:weapon" default="0"/>
    </complexType>

    <complexType name="support">
        <sequence>
            <element name="ammo" type="tns:ammo"/>
            <element name="AARocket" type="tns:AARocket"/>
            <element name="AERocket" type="tns:AERocket"/>
        </sequence>
    </complexType>

    <complexType name="destroyer">
        <sequence>
            <element name="ammo" type="tns:ammo"/>
            <element name="AARocket" type="tns:AARocket"/>
            <element name="AERocket" type="tns:AERocket"/>
        </sequence>
    </complexType>

    <complexType name="escort">
        <sequence>
            <element name="ammo" type="tns:ammo"/>
            <element name="AARocket" type="tns:AARocket"/>
        </sequence>
    </complexType>

    <complexType name="sniffer">
        <sequence>
            <element name="ammo" type="tns:ammo"/>
            <element name="AARocket" type="tns:AARocket"/>
        </sequence>
    </complexType>

    <complexType name="parameters">
        <attribute name="length" type="tns:parameter" default="0"/>
        <attribute name="weight" type="tns:parameter" default="0"/>
        <attribute name="height" type="tns:parameter" default="0"/>
    </complexType>

    <complexType name="type">
        <choice>
            <element name="support" type="tns:support"/>
            <element name="sniffer" type="tns:sniffer"/>
            <element name="destroyer" type="tns:destroyer"/>
            <element name="escort" type="tns:escort"/>
            <element name="scout"/>
        </choice>
    </complexType>

    <complexType name="chars">
        <sequence>
            <element name="type" type="tns:type"/>
        </sequence>
    </complexType>

    <complexType name="content">
        <sequence>
            <element name="model" type="string"/>
            <element name="origin" type="string"/>
            <element name="chars" type="tns:chars"/>
            <element name="parameter" type="tns:parameters"/>
            <element name="price" type="positiveInteger"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>

    <complexType name="plane">
        <sequence>
            <element name="plane" maxOccurs="unbounded" type="tns:content"/>
        </sequence>
    </complexType>

    <element name="planes" type="tns:plane"/>
</schema>

=== MagisterVasader/Epam-labs/lab-3-maven/src/main/resources/planes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://www.example.org/planes" xsi:schemaLocation="https://www.example.org/planes planes.xsd">

    <plane id="id1">
        <model>model1</model>
        <origin>origin1</origin>
        <chars>
            <type>
                <destroyer>
                    <ammo weapon="12.7"/>
                    <AARocket>2</AARocket>
                    <AERocket>4</AERocket>
                </destroyer>
            </type>
            <capacity>1</capacity>
        </chars>
        <parameter length="12.5" weight="5.8" height="3.2"/>
        <price>120000</price>
    </plane>

    <plane id="id2">
        <model>model2</model>
        <origin>origin2</origin>
        <chars>
            <type>
                <support>
                    <ammo/>
                    <AARocket>20</AARocket>
                    <AERocket>10</AERocket>
                </support>
            </type>
            <capacity>2</capacity>
        </chars>
        <parameter/>
        <price>30000</price>
    </plane>

    <plane id="id3">
        <model>model3</model>
        <origin>origin3</origin>
        <chars>
            <type>
                <escort>
                    <ammo/>
                    <AARocket>5</AARocket>
                </escort>
            </type>
            <capacity>1</capacity>
        </chars>
        <parameter/>
        <price>1200000</price>
    </plane>

    <plane id="id4">
        <model>model4</model>
        <origin>origin4</origin>
        <chars>
            <type>
                <scout/>
            </type>
            <capacity>1</capacity>
        </chars>
        <parameter/>
        <price>900000</price>
    </plane>

    <plane id="id5">
        <model>model5</model>
        <origin>origin5</origin>
        <chars>
            <type>
                <sniffer>
                    <ammo/>
                    <AARocket>18</AARocket>
                </sniffer>
            </type>
            <capacity>1</capacity>
        </chars>
        <parameter/>
        <price>550000</price>
    </plane>

</planes>

=== MagisterVasader/Epam-labs/lab-3-maven/src/main/resources/planes-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.example.org/planes"
        xsi:schemaLocation="https://www.example.org/planes planes.xsd">
    <plane id="id2">
        <model><![CDATA[model2]]></model>
        <origin>origin2</origin>
        <chars>
            <type>
                <support>
                    <ammo></ammo>
                    <AARocket>20</AARocket>
                    <AERocket>10</AERocket>
                </support>
            </type>
            <capacity>2</capacity>
        </chars>
        <parameter length="0.0" weight="0.0" height="0.0"></parameter>
        <price>30000</price>
    </plane>
    <plane id="id1">
        <model><![CDATA[model1]]></model>
        <origin>origin1</origin>
        <chars>
            <type>
                <destroyer>
                    <ammo weapon="12.7"></ammo>
                    <AARocket>2</AARocket>
                    <AERocket>4</AERocket>
                </destroyer>
            </type>
            <capacity>1</capacity>
        </chars>
        <parameter length="12.5" weight="5.8" height="3.2"></parameter>
        <price>120000</price>
    </plane>
    <plane id="id5">
        <model><![CDATA[model5]]></model>
        <origin>origin5</origin>
        <chars>
            <type>
                <sniffer>
                    <ammo></ammo>
                    <AARocket>18</AARocket>
                </sniffer>
            </type>
            <capacity>1</capacity>
        </chars>
        <parameter length="0.0" weight="0.0" height="0.0"></parameter>
        <price>550000</price>
    </plane>
    <plane id="id4">
        <model><![CDATA[model4]]></model>
        <origin>origin4</origin>
        <chars>
            <type>
                <scout></scout>
            </type>
            <capacity>1</capacity>
        </chars>
        <parameter length="0.0" weight="0.0" height="0.0"></parameter>
        <price>900000</price>
    </plane>
    <plane id="id3">
        <model><![CDATA[model3]]></model>
        <origin>origin3</origin>
        <chars>
            <type>
                <escort>
                    <ammo></ammo>
                    <AARocket>5</AARocket>
                </escort>
            </type>
            <capacity>1</capacity>
        </chars>
        <parameter length="0.0" weight="0.0" height="0.0"></parameter>
        <price>1200000</price>
    </plane>
</planes>
